spring:
  datasource:
    url: jdbc:mysql://116.62.102.175:3306/dyw?serverTimezone=UTC  #阿里云mysql docker
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 116.62.102.175  #redis主机地址(阿里云redis docker)
logging.level.com.dyw.springboot_cache: debug
logging:
  level: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081

